language: python
os:
  - linux
#  - osx
python:
  - "2.7"
#  - "3.4"
#  - "3.5"
  - "3.6"
install:
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install coverage coveralls
  - pip install -r requirements.txt
script:
  - coverage run --source great_expectations -m unittest tests
  - coveralls
